### DISCUSSION TITLE
How to apply offset to injected language

### DISCUSSION THREAD

**Discussion by joshzcold** [nvim-treesitter/nvim-treesitter#7831] [Q&A]
Injecting markdown into yaml.

```yaml
issues:
  - type: Story
    title: ""
    project_key: DV6
    description: |
      # MARKDOWN

      - Test

      ## Hello
    story_point_estimate:  1
    acceptance_criteria: |
      
    transition_type_name: Dev Ready
```

Query
```scm
(block_node
  (block_mapping
    (block_mapping_pair
      key: (flow_node) @yaml_key
      value: (block_node
        (block_sequence
          (block_sequence_item) *
          (block_sequence_item
            (block_node
              (block_mapping
                (block_mapping_pair) *
                (block_mapping_pair
                  key: (flow_node) @jira_key_field
                  (#any-of? @jira_key_field "description")
                  value: (block_node) 
                ) @injection.content
                (#offset! @injection.content 1 0 0 0)
              )
            )
          )
        )
      )
    )
  )
  (#any-of? @yaml_key "issues")
  (#set! injection.include-children)
  (#set! injection.language "markdown")
)
```

Result

![image](https://github.com/user-attachments/assets/b6548d57-39e5-4b9c-9135-d9ee431a267f)

![image](https://github.com/user-attachments/assets/bf1c1830-4d2d-4432-a5bd-e9c5422ed367)

Subsequent lines after the first line of `section` in `markdown` has the leading whitespace from the `yaml` document.

How do I treat 
```markdown
      # MARKDOWN

      - Test
      - Test
      - Test
      - Test
      - Test
      - Test

      ## Hello
```
Like it isn't indented after injection?
