### ISSUE TITLE
[markdown] yaml codeblock is broken

### ISSUE THREAD

**Issue by numToStr** [nvim-treesitter/nvim-treesitter#3112]
### Describe the bug

Yaml codeblock is not parsed correctly. But inside a yaml file, code is parsed and highlighted correctly.

(I am not sure whether this is a issue with nvim-treesitter or the markdown parser itself)

### To Reproduce

1. Create a `markdown` file
2. Create a ` ```yaml ``` ` codeblock
3. Paste the following inside the codeblock
```yaml
name: lemmy-help

on: [push]

env:
  PROJECT_NAME: awesome-plugin

jobs:
  docs:
    runs-on: ubuntu-latest
    name: emmylua to vimdoc
    steps:
      - uses: actions/checkout@v2

      - name: Generating help
        id: lemmyhelp
        uses: numToStr/lemmy-help@main
        with:
          args: --prefix-class --prefix-alias
          path: |
            path/to/first/file.lua
            path/to/first/second.lua
            path/to/first/third.lua

      - name: Creating help file
        run: echo "${{ steps.lemmyhelp.outputs.doc }}" > ./doc/${PROJECT_NAME}.txt

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore(docs): generate"
          branch: ${{ github.head_ref }}
```
4. See the broken highlights

### Expected behavior

Codeblock should be parsed and highlighted correctly

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - WARNING: `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
  - OK: `node` found v16.15.1 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: cc (GCC) 12.1.0
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - markdown       y . y . y
  - yaml           y y y y y
  - markdown_inliney . . . y
```

### Output of `nvim --version`

```text
NVIM v0.8.0-dev+547-ge837f29ce
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

#### Screenshot

![image](https://user-images.githubusercontent.com/24727447/177031629-317a560f-f41c-41df-9cc9-c70cd91b0f03.png)
